### ISSUE TITLE
Artworks id array

### ISSUE THREAD

**Issue by SupertigerDev** [magne4000/ts-apicalypse#2]
Hello, i got this code
```js
  const { data } = await client.request('games')
      .pipe(
        where('name', "=", "Overwatch"),
        fields(['artworks']),
      ).execute()
      // console.log(data)

      console.log(data[0].artworks)

```
which returns an array of ids im assuming.

How can i get the image url from the list of ids? i tried using the "artworks" request but not sure how to input the id.

**Comment by SupertigerDev** [comment]
Fixed it by doing this:
```js
fields(['artworks.url']),
```

**Comment by SupertigerDev** [comment]
but the images seem to be really small 🤔

**Comment by magne4000** [comment]
Images sizes are explained on official documentation https://api-docs.igdb.com/#images
