### ISSUE TITLE
`ts-toolbelt` should be in `dependencies`, not `devDependencies`

### ISSUE THREAD

**Issue by notjosh** [magne4000/ts-apicalypse#3]
Hiya 👋 

I was having trouble getting the typechecking working - everything was just `any`. After some debugging, it turned out `ts-toolbelt` wasn't installed. After manually installing it, I'm seeing the typechecking working again :)

I see that it's in `devDependencies` of both projects here. Can we move it to `dependencies`, or at least, `peerDependencies`?

Thanks!

**Comment by magne4000** [comment]
Fixed in `0.4.1`
